batch_size: 16                          # batch size
warm_up: 10                             # warm-up epochs
epochs: 1                               # total number of epochs

load_model: None                        # resume training
save_every_n_epochs: 5                  # automatic model saving frequecy

fp16_precision: False                   # float precision 16 (i.e. True/False)
init_lr: 0.0005                         # initial learning rate for Adam
weight_decay: 1e-5                      # weight decay for Adam
gpu: cuda:2                             # training GPU 

model_type: gin                         # GNN backbone (i.e., gin/gcn)
model: 
  num_layer: 5                          # number of graph conv layers
  emb_dim: 300                          # embedding dimension in graph conv layers
  feat_dim: 768                         # output feature dimention
  drop_ratio: 0                         # dropout ratio
  pool: mean                            # readout pooling (i.e., mean/max/add)

aug: node                               # molecule graph augmentation strategy (i.e., node/subgraph/mix)
dataset:
  num_workers: 12                       # dataloader number of workers
  valid_size: 0.05                      # ratio of validation data
  data_path: data/pubchem-10m-clean.txt # path of pre-training data

loss:
  temperature: 0.1                      # temperature of NT-Xent loss
  use_cosine_similarity: True           # whether to use cosine similarity in NT-Xent loss (i.e. True/False)

loss_params:
  alpha: 0.005                          # weight for bert loss
  beta: 0.02                            # weight for graph_model loss
  gamma: 10.0                           # weight for bimodal loss
